"""add settlement idempotency key

Revision ID: 8432e7d09e5e
Revises: e37ec25c5c14
Create Date: 2026-09-03 16:07:53.244308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8432e7d09e5e'
down_revision: Union[str, Sequence[str], None] = 'e37ec25c5c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settlements', sa.Column('idempotency_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_settlements_idempotency_key'), 'settlements', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlements_idempotency_key'), table_name='settlements')
    op.drop_column('settlements', 'idempotency_key')
    # ### end Alembic commands ###
