"""create expenses and expense splits

Revision ID: c8f9c45d9e48
Revises: fc9b19eeff23
Create Date: 2026-08-31 13:17:52.268893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f9c45d9e48'
down_revision: Union[str, Sequence[str], None] = 'fc9b19eeff23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('split_type', sa.Enum('EQUAL', 'EXACT', 'PERCENTAGE', name='expense_split_type'), nullable=False),
    sa.Column('paid_by_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_amount > 0', name='ck_expenses_total_amount_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_created_by_id'), 'expenses', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_expenses_group_id'), 'expenses', ['group_id'], unique=False)
    op.create_index(op.f('ix_expenses_paid_by_id'), 'expenses', ['paid_by_id'], unique=False)
    op.create_table('expense_splits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_expense_splits_amount_non_negative'),
    sa.CheckConstraint('percentage IS NULL OR (percentage >= 0 AND percentage <= 100)', name='ck_expense_splits_percentage_range'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_id', 'user_id', name='uq_expense_splits_expense_user')
    )
    op.create_index(op.f('ix_expense_splits_expense_id'), 'expense_splits', ['expense_id'], unique=False)
    op.create_index(op.f('ix_expense_splits_user_id'), 'expense_splits', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_splits_user_id'), table_name='expense_splits')
    op.drop_index(op.f('ix_expense_splits_expense_id'), table_name='expense_splits')
    op.drop_table('expense_splits')
    op.drop_index(op.f('ix_expenses_paid_by_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_group_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_created_by_id'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
